<h1 style = "color : Brown">NumPy</h1>

- __NumPy__ is a Python library.
- It is used for working with arrays.
- It is short for "Numerical Python".
- It is used for computation and processing of single and multi dimensional array of elements.
- Smaller memory consumption and better runtime behavior.
- Faster than loops, list comprehension, etc.

In [2]:
# To install the library

!pip install -q numpy

## Basic Operations

In [3]:
import numpy as np

In [10]:
a = np.array([[1,2,3,4]])
print(a)
type(a)

[[1 2 3 4]]


numpy.ndarray

In [ ]:
type(a)

numpy.ndarray

In [26]:
a = np.array([1,2,3], dtype = float)
print(a)


[1. 2. 3.]


In [21]:
b = np.array([[1,2,3], [4,5,6],[8,9,10]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [22]:
type(b)

numpy.ndarray

In [23]:
c = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(c)
type(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


numpy.ndarray

In [24]:
#Get Dimensions of a numpy array
print(a.ndim)
print(b.ndim)
print(c.ndim)

4
2
3


In [ ]:
#Get Dimensions of a numpy array
b.ndim

2

In [31]:
c.ndim

2

In [3]:
d = np.array([[[[1,2,3], [4,5,6], [7,8,9]]]])
print(d)
print(d.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
4


In [4]:
d.ndim

4

## Why Use NumPy?

- In Traditional Python Programming, we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to __50x__ faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

## Time taken for the loop

- Dimension (axis) = how many levels of nesting your data has.
- Shape = how many elements are along each axis
- NumPy just counts how deeply nested your brackets are.
- Each new [ introduces a new dimension.
- Inside, it checks the lengths to determine the size along each axis.


| Array type | Example                                     | Shape       | Meaning                             |
| ---------- | ------------------------------------------- | ----------- | ----------------------------------- |
| **1D**     | `[1, 2, 3]`                                 | `(3,)`      | 3 numbers in a row                  |
| **2D**     | `[[1,2,3],[4,5,6]]`                         | `(2,3)`     | 2 rows × 3 columns                  |
| **3D**     | `[[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]` | `(2,2,3)`   | 2 blocks × 2 rows × 3 cols          |
| **4D**     | `[[[[1,2,3],[4,5,6],[7,8,9]]]]`             | `(1,1,3,3)` | 1 group × 1 block × 3 rows × 3 cols |



print(d.ndim)   # number of dimensions


print(d.shape)  # size of each dimension


print(d.size)   # total number of elements


In [34]:
a = np.array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])
print(a)
print(a.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]
2


In [37]:
#Get a shape of a numpy array
a.shape

(3, 3)

In [38]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [39]:
b.shape

(3, 3)

In [40]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [42]:
print(c.shape)
print(c.ndim)
print(c.size)

(1, 3, 3)
3
9


In [43]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [44]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [45]:
a.dtype

dtype('int64')

In [46]:
a_int = np.array([1.1,2.1,3.4])
print(a_int)

[1.1 2.1 3.4]


In [47]:
a_int.dtype

dtype('float64')

## Accessing/Changing specific elements, rows & columns etc.

In [50]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [52]:
a.ndim
a.shape

(2, 7)

In [65]:
#Get a specific element [r,c]
print(a[0,3])
print(a[0,2:-1:2],a[1,2:-1:2])
print(a.shape)

4
[3 5] [10 12]
(2, 7)


In [66]:
a[1,0]

np.int64(8)

In [68]:
print(a[1,5])

13


In [73]:
#Get a specific row from a numpy array
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [74]:
#Get a specific column from a numpy array

a[:,0]

array([1, 8])

In [75]:
#Get a specific column from a numpy array
a[:,0]

array([1, 8])

In [76]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [77]:
a[0,3] = 40
print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [78]:
#Change the 5th column in 1st row to 50
a[0,4] = 50

In [81]:
a

array([[ 1,  2,  3, 40, 50,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

## Zeros/Ones method in NumPy

In [83]:
np.zeros((3,3),dtype=int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
zeros = np.zeros((4,4),dtype=int,order='C')
print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [85]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [86]:
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [88]:
np.full((3,3), 50, dtype='float64')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [89]:
np.full((3,3), 50, dtype='int32')

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]], dtype=int32)

In [90]:
np.random.rand(4,4)

array([[0.83549069, 0.04211113, 0.49230279, 0.68126524],
       [0.77330282, 0.55963679, 0.05780607, 0.51427061],
       [0.37608483, 0.90040838, 0.73861951, 0.52935372],
       [0.14175225, 0.66323476, 0.56864269, 0.73801672]])

In [92]:
np.random.randint(-4,1, size=(3,3))

array([[-3, -2,  0],
       [-2, -3, -1],
       [-1, -1,  0]])

In [91]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Practice Questions

## Question #1

Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [93]:
2,3,4,5,6
20,30,40,50,60
12,12,12,12,12

(12, 12, 12, 12, 12)

In [97]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])
# GBRC -> group, block, row, column
print(a[:3,-5:])

[[ 2  3  4  5  6]
 [20 30 40 50 60]
 [12 12 12 12 12]]


In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [ ]:
a[ :3 , -5: ]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

## Question #2

Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

Examples:

Input 1:

3

Output 1:

[[0 1 0]

 [1 1 1]

 [0 1 0]]

Input 2:

5

Output 1:

[[0 0 1 0 0]

 [0 0 1 0 0]

 [1 1 1 1 1]

 [0 0 1 0 0]

 [0 0 1 0 0]]

In [115]:
n=3

In [118]:
import numpy as np

# Create an (nxn) array with all zeros
z = np.zeros((n,n), dtype='int')
print(z)

z[:,n//2 ] = 1
z[n//2 ,] = 1
print(z)



[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 1 0]
 [1 1 1]
 [0 1 0]]


In [ ]:
# Make the middle row and column all 1s

z[n//2,:] = 1
z[:,n//2] = 1

# Print the final value of z
print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


#### Just to help you understand about n//2

In [ ]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [ ]:
a[5//2,:]=1

In [ ]:
a[:,5//2]=1

In [ ]:
a

array([[ 1,  2,  1,  4,  5,  6],
       [10, 20,  1, 40, 50, 60],
       [ 1,  1,  1,  1,  1,  1],
       [11, 21,  1, 41, 51, 61],
       [13, 24,  1, 44, 54, 64]])

In [ ]:
a[5//2,:] = 1
print(a)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21 31 41 51 61]
 [13 24 34 44 54 64]]


In [ ]:
a[:,n//2] = 1
print(a)

[[ 1  2  1  4  5  6]
 [10 20  1 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21  1 41 51 61]
 [13 24  1 44 54 64]]


## Arithmetic Operations with NumPy - Maths + Stats

In [138]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [120]:
a+2

array([3, 4, 5, 6])

In [121]:
#DO it for -, /, *, //, ** - ALmost all the operations are satisfied

a**3

array([ 1,  8, 27, 64])

In [122]:
a

array([1, 2, 3, 4])

In [123]:
a.min()

np.int64(1)

In [124]:
np.min(a)

np.int64(1)

In [125]:
a.max()

np.int64(4)

In [126]:
np.max(a)

np.int64(4)

In [127]:
a.mean()

np.float64(2.5)

In [128]:
np.mean(a)

np.float64(2.5)

In [129]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [130]:
np.max(a)

np.int64(8)

In [131]:
a.max()

np.int64(8)

In [ ]:
np.min(a)

1

In [132]:
np.mean(a)

np.float64(4.5)

In [141]:
np.sum(a)
print(a)

[1 2 3 4]


In [142]:
np.max(a, axis=0])

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (ipython-input-2743854062.py, line 1)

In [143]:
np.max(a, axis=0)

np.int64(4)

In [144]:
np.min(a, axis=0)

np.int64(1)

In [146]:
np.min(a, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
np.sum(a, axis=1)

array([10, 26])

In [ ]:
np.sum(a, axis=0)

array([ 6,  8, 10, 12])