<h1 style = "color : Brown">NumPy</h1>

- __NumPy__ is a Python library.
- https://numpy.org/
- It is used for working with arrays.
- It is short for "Numerical Python".
- It is used for computation and processing of single and multi dimensional array of elements.
- Smaller memory consumption and better runtime behavior.
- Faster than loops, list comprehension, etc.

- Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.
- NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

- Open Source
- Pretty fast and uses VECTORS (vectorized operations, no explicit loops)
- Memory efficient
- best for numberical computations
- broadcating - operate on arrays of different shapes
- comes with powerful linear algebra, random tools etc.

- Use of NUMPY
  - scientific python
  

- UV installation

		# uv init --python 3.14 <project-name>
		# cd <project-name>
		# uv sync 				# sync with all the project files and create .venv directory
								# will see everything in pyproject.toml file and install the required items mentioned in the .toml file
								# uv is required so that we can create a .toml file
								# yv sync will be able to install everything mentioned in the .toml file

		# uv add ipykernel 		# add ipykernel
		# uv add numpy 			# level2 		.toml should be updated after this
		# uv pip install numpy 	# level 1


		# !pip install numpy


  - NUMPY ARRAY
   []       - 1d
   [[]]     - 2d
   [[[]]]   - 3d   
   [[[[]]]] - 4d

In [4]:
# To install the library

!pip install -q numpy

## Basic Operations

In [5]:
import numpy as np

In [7]:
arr_1 = np.array([1,2,3]) # array is numpy array
print(arr_1)
print(type(arr_1))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
arr_2 = np.array([[1,2,3],[4,5,6]]) # array is numpy array
print(arr_2)
print(type(arr_2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


- numpy array

- numpy datatypes
  - np.int8        - 8 bits to represent 1 number
  - np.int16       - 16 bits to represent 1 number
  - np.int32       - 32 bits to represent 1 number
  - np.uint128
  - np.uint64

In [10]:
arr_4 = np.array([10, 12, 13], dtype=np.int8)
print(arr_4)
print(type(arr_4))    # defing the data type as int8 instead of default int64
                      # This will reduce the computing power
                      # Quantization - process of reducing the size and reduce the precision
                      # reduce size but with less precision

[10 12 13]
<class 'numpy.ndarray'>


In [11]:
arr_4 = np.array([10, 12, 13, "hello"], dtype=np.int8) # will give error
# data types in the array could be only of 1 type


ValueError: invalid literal for int() with base 10: 'hello'

In [16]:
arr_4 = np.array([10, 12, 13, "hello"]) # Array will have element of only 1 data type
print(arr_4)
print(type(arr_4))
print(arr_4[1].dtype)
print(type(arr_4[1]))  # even integers are converted to string
                       # data types becomes similar of all the elements in the array
                       # numpy tries to convert all the data types in such a way to avoid any error

['10' '12' '13' 'hello']
<class 'numpy.ndarray'>
<U2
<class 'numpy.str_'>


In [19]:
# range in numpy
# np.arange(start,stop,step)
a = np.arange(1,10,2)
print(a)
b = np.array(np.arange(1,10,2))
print(b)

[1 3 5 7 9]
[1 3 5 7 9]


In [22]:
# np.linspace(start,stop,num=x) # stop is inclusive

a = np.linspace(1,100,4)      # give me 4 different numbers separated by 4 between 1-100
                              # equally divide 1-100 into 4 equal spaced numbers
                              # 4 numbers and 3 spaces
print(a)
print(type(a))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [30]:
a = np.linspace(1,10,5)      # give me 10 different numbers separated between 1-100
                              # equally divide 1-10 into 10 equal spaced numbers
                              # 10 numbers and 3 spaces
                              # linspace generated sample within start,stop (inclusive) seperated by step numbers
                              # sicne, its generating numbers we can iterate over it
print(a)
print(type(a))

for i in np.linspace(1,10,5,dtype=np.int8):
  print(i)

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>
1
3
5
7
10


In [41]:
# Shape of matric
# np.zeros(shape) # will allow you to create elements of all 0s of specific size
# matrix is a grid of numbers have rows and columns
# size of matrix
# elements in a matrix
print(np.zeros(3,dtype=int))
#print(np.zeros((2,5,5),dtype=int)) # create 5 matrix of size 5*5
b = np.zeros((1,5,5,5),dtype=int) # create 2 matrix of size 5*5
print(b)
#np.zeros((3,3),dtype=int)
print(b.ndim)



[0 0 0]
[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]]
4


In [42]:
# Shape of matric
# np.ones(shape) # will allow you to create elements of all 1s of specific size
# matrix is a grid of numbers have rows and columns
# size of matrix
# elements in a matrix
print(np.ones(3,dtype=int))
#print(np.ones((2,5,5),dtype=int)) # create 5 matrix of size 5*5
b = np.ones((1,5,5,5),dtype=int) # create 2 matrix of size 5*5
print(b)
#np.ones((3,3),dtype=int)
print(b.ndim)

[1 1 1]
[[[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]]
4


In [45]:
#np.full(shape,value-to-fill)
npf_1 = np.full((2,3),5)
print(npf_1)

[[5 5 5]
 [5 5 5]]


In [ ]:
# identity matrix
# does not exist in 1 D
# minimum of 2 D is requierd
np.eye(3,3)
np.eye(3,3) # better to have similar size in rows and columns
np.eye(1,1)

In [49]:
# Create empty array and fill the values later on
# np.empty(shape)
# garbage collection is responsible to clean heap memory
# just give me a space in the memory with any random values
np.empty((2,2),dtype=np.int8)
np.empty((2,2),dtype=np.int16)
np.empty((2,2),dtype=int)
# you will get some random dummy values

array([[4607182418800017408, 4629981891913580544],
       [4634415122796773376, 4636737291354636288]])

In [51]:
# check the total execution time for np.emtpy and np.ones()
import time
start_time = time.time()
np.empty((2,2),dtype=np.int8)
end_time = time.time()
print(end_time - start_time)

start_time = time.time()
np.ones((2,2),dtype=np.int8)
end_time = time.time()
print(end_time - start_time)

0.00012922286987304688
0.0001518726348876953


In [ ]:
## Calculate Variance with NUMPY

data = np.array([10, 12, 13])
print(data)


population_var = np.var(data)
# var stands for variance—the average squared distance from the mean.
# By default, NumPy divides by N (the total number of elements).
# Use this when your array represents the entire population and you don’t need Bessel’s correction.

sample_var = np.var(data, ddof=1)
# ddof means Delta Degrees Of Freedom.
# Setting ddof=1 tells NumPy to divide by N - 1 instead of N.
# The “minus 1” is Bessel’s correction, giving an unbiased estimate of the population variance when you only have a sample.

print(population_var, sample_var)

[10 12 13]
1.5555555555555556 2.3333333333333335


In [ ]:
a = np.array([[1,2,3,4]])
print(a)
type(a)

[[1 2 3 4]]


numpy.ndarray

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a = np.array([1,2,3], dtype = float)
print(a)


[1. 2. 3.]


In [ ]:
b = np.array([[1,2,3], [4,5,6],[8,9,10]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(c)
type(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


numpy.ndarray

In [ ]:
#Get Dimensions of a numpy array
print(a.ndim)
print(b.ndim)
print(c.ndim)

4
2
3


In [ ]:
#Get Dimensions of a numpy array
b.ndim

2

In [ ]:
c.ndim

2

In [ ]:
d = np.array([[[[1,2,3], [4,5,6], [7,8,9]]]])
print(d)
print(d.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
4


In [ ]:
d.ndim

4

## Why Use NumPy?

- In Traditional Python Programming, we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to __50x__ faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

## Time taken for the loop

- Dimension (axis) = how many levels of nesting your data has.
- Shape = how many elements are along each axis
- NumPy just counts how deeply nested your brackets are.
- Each new [ introduces a new dimension.
- Inside, it checks the lengths to determine the size along each axis.


| Array type | Example                                     | Shape       | Meaning                             |
| ---------- | ------------------------------------------- | ----------- | ----------------------------------- |
| **1D**     | `[1, 2, 3]`                                 | `(3,)`      | 3 numbers in a row                  |
| **2D**     | `[[1,2,3],[4,5,6]]`                         | `(2,3)`     | 2 rows × 3 columns                  |
| **3D**     | `[[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]` | `(2,2,3)`   | 2 blocks × 2 rows × 3 cols          |
| **4D**     | `[[[[1,2,3],[4,5,6],[7,8,9]]]]`             | `(1,1,3,3)` | 1 group × 1 block × 3 rows × 3 cols |



print(d.ndim)   # number of dimensions


print(d.shape)  # size of each dimension


print(d.size)   # total number of elements


In [ ]:
a = np.array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])
print(a)
print(a.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]
2


In [ ]:
#Get a shape of a numpy array
a.shape

(3, 3)

In [ ]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
b.shape

(3, 3)

In [ ]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
print(c.shape)
print(c.ndim)
print(c.size)

(1, 3, 3)
3
9


In [ ]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a_int = np.array([1.1,2.1,3.4])
print(a_int)

[1.1 2.1 3.4]


In [ ]:
a_int.dtype

dtype('float64')

## Accessing/Changing specific elements, rows & columns etc.

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a.ndim
a.shape

(2, 7)

In [ ]:
#Get a specific element [r,c]
print(a[0,3])
print(a[0,2:-1:2],a[1,2:-1:2])
print(a.shape)

4
[3 5] [10 12]
(2, 7)


In [ ]:
a[1,0]

np.int64(8)

In [ ]:
print(a[1,5])

13


In [ ]:
#Get a specific row from a numpy array
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific column from a numpy array

a[:,0]

array([1, 8])

In [ ]:
#Get a specific column from a numpy array
a[:,0]

array([1, 8])

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
a[0,3] = 40
print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Change the 5th column in 1st row to 50
a[0,4] = 50

In [ ]:
a

array([[ 1,  2,  3, 40, 50,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

## Zeros/Ones method in NumPy

In [ ]:
np.zeros((3,3),dtype=int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
zeros = np.zeros((4,4),dtype=int,order='C')
print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
np.full((3,3), 50, dtype='float64')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [ ]:
np.full((3,3), 50, dtype='int32')

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]], dtype=int32)

In [ ]:
np.random.rand(4,4)

array([[0.83549069, 0.04211113, 0.49230279, 0.68126524],
       [0.77330282, 0.55963679, 0.05780607, 0.51427061],
       [0.37608483, 0.90040838, 0.73861951, 0.52935372],
       [0.14175225, 0.66323476, 0.56864269, 0.73801672]])

In [ ]:
np.random.randint(-4,1, size=(3,3))

array([[-3, -2,  0],
       [-2, -3, -1],
       [-1, -1,  0]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Practice Questions

## Question #1

Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [ ]:
2,3,4,5,6
20,30,40,50,60
12,12,12,12,12

(12, 12, 12, 12, 12)

In [ ]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])
# GBRC -> group, block, row, column
print(a[:3,-5:])

[[ 2  3  4  5  6]
 [20 30 40 50 60]
 [12 12 12 12 12]]


In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [ ]:
a[ :3 , -5: ]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

## Question #2

Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

Examples:

Input 1:

3

Output 1:

[[0 1 0]

 [1 1 1]

 [0 1 0]]

Input 2:

5

Output 1:

[[0 0 1 0 0]

 [0 0 1 0 0]

 [1 1 1 1 1]

 [0 0 1 0 0]

 [0 0 1 0 0]]

In [ ]:
n=3

In [ ]:
import numpy as np

# Create an (nxn) array with all zeros
z = np.zeros((n,n), dtype='int')
print(z)

z[:,n//2 ] = 1
z[n//2 ,] = 1
print(z)



[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 1 0]
 [1 1 1]
 [0 1 0]]


In [ ]:
# Make the middle row and column all 1s

z[n//2,:] = 1
z[:,n//2] = 1

# Print the final value of z
print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


#### Just to help you understand about n//2

In [ ]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [ ]:
a[5//2,:]=1

In [ ]:
a[:,5//2]=1

In [ ]:
a

array([[ 1,  2,  1,  4,  5,  6],
       [10, 20,  1, 40, 50, 60],
       [ 1,  1,  1,  1,  1,  1],
       [11, 21,  1, 41, 51, 61],
       [13, 24,  1, 44, 54, 64]])

In [ ]:
a[5//2,:] = 1
print(a)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21 31 41 51 61]
 [13 24 34 44 54 64]]


In [ ]:
a[:,n//2] = 1
print(a)

[[ 1  2  1  4  5  6]
 [10 20  1 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21  1 41 51 61]
 [13 24  1 44 54 64]]


## Arithmetic Operations with NumPy - Maths + Stats

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
print("min : ", a.min())
print("max : ", a.max())
print("mean : ", a.mean())
print("median : ", a.median())
print("mode : ", a.mode())

min :  1
max :  4
mean :  2.5


AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
#DO it for -, /, *, //, ** - ALmost all the operations are satisfied

a**3

array([ 1,  8, 27, 64])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.min()

np.int64(1)

In [ ]:
np.min(a)

np.int64(1)

In [ ]:
a.max()

np.int64(4)

In [ ]:
np.max(a)

np.int64(4)

In [ ]:
a.mean()

np.float64(2.5)

In [ ]:
np.mean(a)

np.float64(2.5)

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.max(a)

np.int64(8)

In [ ]:
a.max()

np.int64(8)

In [ ]:
np.min(a)

1

In [ ]:
np.mean(a)

np.float64(4.5)

In [ ]:
np.sum(a)
print(a)

[1 2 3 4]


In [ ]:
np.max(a, axis=0])

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (ipython-input-2743854062.py, line 1)

In [ ]:
np.max(a, axis=0)

np.int64(4)

In [ ]:
np.min(a, axis=0)

np.int64(1)

In [ ]:
np.min(a, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
np.sum(a, axis=1)

array([10, 26])

In [ ]:
np.sum(a, axis=0)

array([ 6,  8, 10, 12])